# IR-004 – Suspicious PowerShell Attack Investigation

## Executive Summary

A simulated PowerShell attack was executed in a controlled lab environment to validate endpoint detection and SIEM monitoring capabilities.

The attack included multiple stages including process creation, account discovery, Base64 encoded PowerShell execution, and an executable file drop.

All stages were successfully detected by Wazuh using Sysmon telemetry.

---

## Incident Severity

**High**

---

## Date

July 2026

---

## Environment

- Windows 11 Endpoint
- Ubuntu 24.04 Wazuh Manager
- Wazuh SIEM
- Microsoft Sysmon
- VirtualBox Lab

---

## Objective

Validate that Wazuh successfully detects suspicious PowerShell activity commonly observed during post-exploitation attacks.

---

## Attack Timeline

### Stage 1

PowerShell process execution detected.

**Evidence**

- Process Creation
- Sysmon Event ID 1

---

### Stage 2

PowerShell executed account discovery commands.

**Detection**

- Account Discovery

MITRE ATT&CK

T1087

Account Discovery

---

### Stage 3

PowerShell executed a Base64 encoded command.

Detection:

Rule ID **92057**

Severity **12**

MITRE ATT&CK

T1059.001

PowerShell

---

### Stage 4

Executable file dropped on disk.

Detection generated by Wazuh.

---

## Detection Summary

| Activity | Status |
|----------|--------|
| Process Creation | Detected |
| PowerShell Discovery | Detected |
| Account Discovery | Detected |
| Encoded PowerShell | Detected |
| Executable Drop | Detected |

---

## MITRE ATT&CK Mapping

- T1059.001 – PowerShell
- T1087 – Account Discovery

---

## Analyst Assessment

The simulated attack demonstrated that Sysmon and Wazuh successfully correlated multiple stages of malicious PowerShell activity.

The SIEM generated alerts throughout the attack chain, providing sufficient visibility for investigation and response.

No actual compromise occurred because this activity was executed within a controlled laboratory environment.

---

## Lessons Learned

- Sysmon significantly improves endpoint visibility.
- Wazuh successfully detected multiple PowerShell attack behaviors.
- Correlating multiple alerts provides better context than investigating isolated events.
- MITRE ATT&CK mapping improves incident classification and reporting.
- ## Evidence

Screenshots:

- powershell-base64-alert.png
- powershell-base64-rule.png
- sysmon-powershell-alert.png
- malware-file-drop-alert.png
- threat-hunting-dashboard.png
